name: ci-test

# Triggers the workflow on push or pull request events
on: [push, pull_request]

jobs:

  test:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6

    - name: Install latest ansible and make the collection available
      run: |
        mkdir -p $HOME/.ansible/collections/ansible_collections/scicore/
        ln -s ${GITHUB_WORKSPACE} $HOME/.ansible/collections/ansible_collections/scicore/guacamole
        ls -la $HOME/.ansible/collections/ansible_collections/scicore/
        ls -la $HOME/.ansible/collections/ansible_collections/scicore/guacamole/
